### ISSUE TITLE
address does not always return result correctly..

### ISSUE THREAD

**Issue by Lucyhutch50** [RynoCoetzee/TRCGPlaceAutoCompleteCombo#3]
If you autocomplete addresses with - in them like

48-48 Princes Places London

although it appears back in the combo box if I select this one and then look at the returned json the 48-49 is missing?

`{"html_attributions":[],"result":{"address_components":[{"long_name":"Princes Place","short_name":"Princes Pl","types":["route"]},{"long_name":"London","short_name":"London","types":["postal_town"]},{"long_name":"Greater London","short_name":"Greater London","types":["administrative_area_level_2","political"]},{"long_name":"England","short_name":"England","types":["administrative_area_level_1","political"]},{"long_name":"United Kingdom","short_name":"GB","types":["country","political"]},{"long_name":"W11","short_name":"W11","types":["postal_code_prefix","postal_code"]}],"adr_address":"<span class=\"street-address\">Princes Place<\/span>, <span class=\"locality\">London<\/span> <span class=\"postal-code\">W11<\/span>, <span class=\"country-name\">UK<\/span>","formatted_address":"Princes Pl, London W11, UK","geometry":{"location":{"lat":51.5080535,"lng":-0.2113078},"viewport":{"northeast":{"lat":51.5094024802915,"lng":-0.209958819708498},"southwest":{"lat":51.5067045197085,"lng":-0.212656780291502}}},"icon":"https:\/\/maps.gstatic.com\/mapfiles\/place_api\/icons\/v1\/png_71\/geocode-71.png","id":"","name":"Princes Place","place_id":"EhpQcmluY2VzIFBsLCBMb25kb24gVzExLCBVSyIuKiwKFAoSCcsjG2XnD3ZIEcbDj0_qaBeXEhQKEgnz8xe3Wxt2SBEKsgA5eS6RSQ","reference":"EhpQcmluY2VzIFBsLCBMb25kb24gVzExLCBVSyIuKiwKFAoSCcsjG2XnD3ZIEcbDj0_qaBeXEhQKEgnz8xe3Wxt2SBEKsgA5eS6RSQ","scope":"","types":["route"],"url":"https:\/\/maps.google.com\/?q=Princes+Pl,+London+W11,+UK&ftid=0x48760fe7651b23cb:0x971768ea4f8fc3c6","utc_offset":60,"vicinity":""},"status":"OK"}`

It just seems inconsistent? Is this a google issue?
thanks
Phil

**Comment by RynoCoetzee** [comment]
Google has some issue with length type street numbers (I.E "48-49") and things like "Corner of Road A and Street B"
